export enum DomainExceptionCode {
	DEFAULT_DOMAIN_EXCEPTION = 'DEFAULT_DOMAIN_EXCEPTION',
	USER_NAME_REQUIRED = 'USER_NAME_REQUIRED',
	USER_LASTNAME_REQUIRED = 'USER_LASTNAME_REQUIRED',
	USER_EMAIL_REQUIRED = 'USER_EMAIL_REQUIRED',
	USER_EMAIL_INVALID = 'USER_EMAIL_INVALID',
	USER_PHONE_REQUIRED = 'USER_PHONE_REQUIRED',
}
